### ISSUE TITLE
post返回：The resource you are looking for has been removed

### ISSUE THREAD

**Issue by 0772boy** [szvone/imgApi#6]
开始测试Api接口...
请求接口：http://0772boy.gearhostpreview.com/public/api
通讯密钥：1

读入图片成功，转换成Base64编码(此处为前50位,后面的省略)：
data:image/jpeg;base64,/9j/4AAQSkZJRgABAgAAAQABAAD

剔除格式信息后进行utf8编码(此处为前50位,后面的省略)：
%2F9j%2F4AAQSkZJRgABAgAAAQABAAD%2F4QDVRXhpZgAASUkq

组合后Post参数(imgBase64为前50位,后面的省略)：
key=1&imgBase64=%2F9j%2F4AAQSkZJRgABAgAAAQABAAD%2F4QDVRXhpZgAASUkq

发起Post请求...

post返回：The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.

http://0772boy.gearhostpreview.com/public/index.html

请问是什么情况。。。？

**Comment by szvone** [comment]
请更改您的伪静态设置，参考资料
https://www.itbulu.com/tp-rwrite.html
